### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by Tom-TBT**
Added maintainer and project URL to the new repo

### CODE REVIEW

**Comment by joshmoore** [comment]
P.S. I added the "omero-web" topic to the two repos.

**Comment by sbesson** [comment]
While reviewing the expectation for the PyPI package, I got slightly confused:

- the GitHub repository is currently named `omero-tagsearch`
- the Python manifest calls it `omero-webtagging-tagsearch` (https://github.com/German-BioImaging/omero-tagsearch/blob/a2d96a7b4b0429c874ea5e0e07b3f1259680f479/setup.py#L31)
- the package name is `omero_webtagging_tagsearch`

Is the goal to publish the new updated package to PyPI as `omero-tagsearch` ? Or keep the statu quo as `omero-webtagging-tagsearch`?

**Comment by joshmoore** [comment]
(good question(s))

**Comment by Tom-TBT** [comment]
That would be cool to use an updated package name, but that's a bit of a scary zone for me. 
So if one of you can double-check what I'm planning on doing that would be great:

https://github.com/German-BioImaging/omero-tagsearch/issues/4

**Pull request merged**
