### PR TITLE
Changing PyPI to omero-tagsearch

### PR DESCRIPTION
**Pull request by Tom-TBT**
Preparing the repo to publish packages to the new PyPI omero-tagsearch:

- [x] Renamed the folder omero_webtagging_tagsearch
- [x] Renamed the folder omero_webtagging_tagsearch/template/omero_webtagging_tagsearch
- [x] Renamed the references to the above changed dir
- [x] Renamed the PyPI reference in README and setup.py
- [x] Added a workflow to publish push of new tags to PyPI
- [ ] Update reference in doc https://omero.readthedocs.io/en/latest/developers/Web/WebclientPlugin.html
- [ ] Update reference in doc https://omero.readthedocs.io/en/latest/developers/Web.html#omero-web
- [x] Add explanation on the update in README
- [x] Test changes (renaming)
- [ ] Publish omero-webtagging-tagsearch 4.0.0 with link to the new PyPI ([throwing error during install](cookie-cutter: https://github.com/simonw/pypi-rename))
- [x] Remove obsolete `release.py`
- [x] Add omero-webtagging-tagsearch to `Obsoletes-Dist` in `setup.py`
- [x] Update of urls.py for Django 4 compatibility

### CODE REVIEW

**Comment by Tom-TBT** [comment]
Addressing the tasks mentioned in https://github.com/German-BioImaging/omero-tagsearch/issues/4

**Comment by Tom-TBT** [comment]
Proposed PR for the doc update: https://github.com/ome/omero-documentation/pull/2327

**Review by will-moore — COMMENTED** [review]
This is being deployed on the OME merge-ci test server with 
```
pip install -i https://test.pypi.org/simple/ omero-tagsearch
```
We have Django 4.2.2 installed there and this is failing with:

```
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 103: 'ifequal', expected 'endwith'. Did you forget to register or load this tag?
```

To support Django 4+ you need to replace `ifequal` tags with `if` tags. E.g. as for webclient: https://github.com/ome/omero-web/pull/458/files#diff-4c8c32d73f9fef6388a145c361bf0882ff4ceaf8ddad90f812393d1dbe475c80

**Review by will-moore — APPROVED** [review]
Installed this branch on our merge-ci with `pip install 'omero-tagsearch @ git+https://github.com/German-BioImaging/omero-tagsearch@workflow_pypi'`
and testing worked fine. 👍

**Pull request merged**
